@port=3000
@jwt={{login.response.body.data.token}}

###
# @name login
POST http://localhost:{{port}}/api/v1/users/login
Content-Type: application/json

{
    "name": "manuelnreyes",
    "password": "wasd123"
}

###
# @name login
POST http://localhost:{{port}}/api/v1/users/login
Content-Type: application/json

{
    "name": "juan",
    "password": "wasd123"
}

###
POST http://localhost:{{port}}/api/v1/users/seed

###
GET http://localhost:{{port}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
GET http://localhost:{{port}}/api/v1/workouts/
Authorization: Bearer {{jwt}}

###
GET http://localhost:{{port}}/api/v1/workouts/6445c926e29bb06eb074fea2
Authorization: Bearer {{jwt}}

###
GET http://localhost:{{port}}/api/v1/workouts/search/march
Authorization: Bearer {{jwt}}

###
GET http://localhost:{{port}}/api/v1/users/search/a
Authorization: Bearer {{jwt}}